In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [11]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [12]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
type(a)

numpy.ndarray

In [14]:
b = np.array([True,False,True])

In [15]:
b

array([ True, False,  True])

In [16]:
c = np.array(['pune','mumbai','nagpur'])

In [17]:
c

array(['pune', 'mumbai', 'nagpur'], dtype='<U6')

In [21]:
d=np.array([5.4,4.4,2.2,7.7])
d

array([5.4, 4.4, 2.2, 7.7])

In [18]:
x={1:1,2:4,3:9}
y = np.array(x)

In [19]:
y

array({1: 1, 2: 4, 3: 9}, dtype=object)

In [20]:
y[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [ ]:
#binary number system  --- 0/1  5======101 
decimal number system --- digits --- 10  ----0,1,2,,...,9
                          bits ----- 2       0,1
8 bits = 1byte
1024 bytes = 1KB
1024KB=1MB
    

In [30]:
a=np.array([3,5,9,2,5],dtype='int8')
a

array([3, 5, 9, 2, 5], dtype=int8)

In [31]:
type(a)

numpy.ndarray

In [32]:
a.dtype

dtype('int8')

In [ ]:
a.ndim

1

In [ ]:
a.shape

(5,)

In [ ]:
a.size

5

In [50]:
a=np.array(
    [
     [3,5,9,2,5],
     [1,2,3,4,5]
    ],dtype='int16')
a

array([[3, 5, 9, 2, 5],
       [1, 2, 3, 4, 5]], dtype=int16)

In [51]:
a.dtype

dtype('int16')

In [52]:
a.ndim

2

In [53]:
a.shape

(2, 5)

In [54]:
a.size

10

In [55]:
#array([3, 5, 9, 2, 5])
b = np.array([
                [9.0,8.0,7.0],
                [6.0,5.0,4.0],
                [6.4,4.0,55.5]
            ])
print(b)

[[ 9.   8.   7. ]
 [ 6.   5.   4. ]
 [ 6.4  4.  55.5]]


In [56]:
b.ndim

2

In [57]:
b.shape

(3, 3)

In [58]:
type(b)

numpy.ndarray

In [59]:
b.dtype

dtype('float64')

In [60]:
a

array([[3, 5, 9, 2, 5],
       [1, 2, 3, 4, 5]], dtype=int16)

In [62]:
#numpy. itemsize. This array attribute returns the length 
#of each element of array in bytes.
a.itemsize

2

In [63]:
a.size

10

In [64]:
b

array([[ 9. ,  8. ,  7. ],
       [ 6. ,  5. ,  4. ],
       [ 6.4,  4. , 55.5]])

In [65]:
b.itemsize

8

In [66]:
b.dtype

dtype('float64')

In [ ]:
b.size

9

### Accessing/Changing specific elements, rows, columns, etc¶

In [67]:
a=np.array([3,5,9,2,5])
a

array([3, 5, 9, 2, 5])

In [68]:
a[2]

9

In [69]:
a[-1]

5

In [70]:
a = np.array([
                [1,2,3,4,5,6,7],#0
                [8,9,10,11,12,13,14]#1
            ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [72]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
a[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [75]:
a[1][2]

10

In [76]:
a[0][2]

3

In [77]:
#a[row, col]
a[0,2]

3

In [84]:
#index slicing
x=np.array([76,43,98,34,2,7,4,2])
x

array([76, 43, 98, 34,  2,  7,  4,  2])

In [85]:
x[0:4]

array([76, 43, 98, 34])

In [86]:
x[3:7]

array([34,  2,  7,  4])

In [92]:
x[0:6:1]

array([76, 43, 98, 34,  2,  7])

In [90]:
#step size
x[0:6:2]

array([76, 98,  2])

In [94]:
a=np.array(
    [
        [ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
        [ 1,  9, 1, 1, 12, 3, 4],
    ])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [ 1,  9,  1,  1, 12,  3,  4]])

In [95]:
#a[row_start:row_end,col_start:col_end]
a[0:1]

array([[1, 2, 3, 4, 5, 6, 7]])

In [96]:
a[0:2]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [97]:
a[1:2]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [98]:
a[-1]

array([ 1,  9,  1,  1, 12,  3,  4])

In [101]:
x=np.array([
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [ 18,  229, 110, 14, 125, 135, 314],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 21,  32,  43,  54,  5,  16,  17]    
])
x

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14],
       [ 18, 229, 110,  14, 125, 135, 314],
       [  1,   2,   3,   4,   5,   6,   7],
       [ 21,  32,  43,  54,   5,  16,  17]])

In [100]:
# r1:r2,c1:c2
x[0:4,0:4]

array([[  1,   2,   3,   4],
       [  8,   9,  10,  11],
       [ 18, 229, 110,  14],
       [  1,   2,   3,   4]])

In [102]:
x[3:,:4]

array([[ 1,  2,  3,  4],
       [21, 32, 43, 54]])

In [103]:
x[3:5,2:4]

array([[ 3,  4],
       [43, 54]])

In [104]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [ 1,  9,  1,  1, 12,  3,  4]])

In [105]:
a[1][2]

10

In [106]:
a[1][2]=100

In [107]:
a

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9, 100,  11,  12,  13,  14],
       [  1,   9,   1,   1,  12,   3,   4]])

In [108]:
a[1,2]=1000
a

array([[   1,    2,    3,    4,    5,    6,    7],
       [   8,    9, 1000,   11,   12,   13,   14],
       [   1,    9,    1,    1,   12,    3,    4]])

In [109]:
a[0]=101

In [110]:
a

array([[ 101,  101,  101,  101,  101,  101,  101],
       [   8,    9, 1000,   11,   12,   13,   14],
       [   1,    9,    1,    1,   12,    3,    4]])

In [111]:
x

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14],
       [ 18, 229, 110,  14, 125, 135, 314],
       [  1,   2,   3,   4,   5,   6,   7],
       [ 21,  32,  43,  54,   5,  16,  17]])

In [112]:
x[:,0:1]=99

In [113]:
x

array([[ 99,   2,   3,   4,   5,   6,   7],
       [ 99,   9,  10,  11,  12,  13,  14],
       [ 99, 229, 110,  14, 125, 135, 314],
       [ 99,   2,   3,   4,   5,   6,   7],
       [ 99,  32,  43,  54,   5,  16,  17]])

In [ ]:
x[:,6:-1]=1000
x

array([[ 99,   2,   3,   4,   5,   6, 100],
       [ 99,   9,  10,  11,  12,  13, 100],
       [ 99, 229, 110,  14, 125, 135, 100],
       [ 99,   2,   3,   4,   5,   6, 100],
       [ 99,  32,  43,  54,   5,  16, 100]])

In [3]:
x2=np.array([
                [1,2,3],
                [5,6,7]
            ])
x2.ndim

2

In [4]:
x2[0,0]
#x2[0][0]

1

In [12]:
b=np.array([
    [
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
]
)

In [14]:
b.dtype

dtype('int64')

In [6]:
b.ndim

3

In [7]:
b[0,0,0]

1

In [8]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
b[0]

array([[1, 2],
       [3, 4]])

In [23]:
b[0,0,1]

2

In [21]:
b[1]

array([[ 5, 66],
       [ 7,  8]])

In [ ]:
b[1,1]

array([7, 8])

In [10]:
b[1,1,1]

8

In [ ]:
b[0,0,1]

2

In [ ]:
b[0,1,1]

4

In [ ]:
 b[1,0,1]

6

In [17]:
 b[1,0,1]=66.77

In [18]:
b.dtype

dtype('int64')

In [19]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5, 66],
        [ 7,  8]]])

In [ ]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5, 66],
        [ 7,  8]]])

In [ ]:
b[0,1]=100

In [ ]:
b

array([[[  1,   2],
        [100, 100]],

       [[  5,  66],
        [  7,   8]]])

###initializing different types of arrays

In [ ]:
x=np.zeros((10,))
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
x=np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
x=np.zeros((2,4,5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [26]:
y=np.ones((5,))
y

array([1., 1., 1., 1., 1.])

In [27]:
y=np.ones((8,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
y=np.ones((3,5),dtype='int16')
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [29]:
z=np.full((5,6),11)
z

array([[11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11]])

In [30]:
x1=np.full_like(z,44)
x1

array([[44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44]])

In [31]:
x1

array([[44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44]])

In [36]:
y1=np.full_like(y,6.7,dtype='float')

In [37]:
y1.dtype

dtype('float64')

In [38]:
y1

array([[6.7, 6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7, 6.7]])

In [42]:
a=np.random.rand(4,4)
a

array([[0.94337603, 0.65824346, 0.3079053 , 0.5311382 ],
       [0.88036878, 0.23654639, 0.69759016, 0.17187903],
       [0.88477036, 0.18596102, 0.62034418, 0.7379822 ],
       [0.52357435, 0.76331874, 0.33105483, 0.76119654]])

In [40]:
x=np.random.randint(1,100)
x

43

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.array([1,2,3,4,5])
a1=np.repeat(a,3)
a1

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [45]:
a=np.array([[1,2,3,4,5]])
a1=np.repeat(a,4,axis=0)#1=row, 0=col
print(a1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
a = np.ones((5,5))
print(a)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

a[1:4,1:4] = z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
b=a
b

array([1, 2, 3, 4])

In [ ]:
b[0]=111
b

array([111,   2,   3,   4])

In [ ]:
a

array([111,   2,   3,   4])

In [ ]:
b=a.copy()

In [ ]:
b[0]=99
b

array([99,  2,  3,  4])

In [52]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [53]:
#Maths

In [54]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [56]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [58]:
a=np.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [60]:
a**2

array([ 1,  4,  9, 16])

In [61]:
a

array([1, 2, 3, 4])

In [62]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [64]:
np.tan(45)

1.6197751905438615

In [65]:
#Linear algebra

In [68]:
a=np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [69]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [70]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.linalg.det(c)

1.0

In [72]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.min()

1

In [ ]:
a.max()

6

In [ ]:
a.mean()

3.5

In [73]:
a.sum()

21

In [74]:
a.std()

1.707825127659933

In [75]:
a.var()

2.9166666666666665

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.min(a,axis=1)

array([1, 4])

In [78]:
np.min(a,axis=0)

array([1, 2, 3])

In [79]:
np.max(a,axis=0)

array([4, 5, 6])

In [80]:
np.sum(a)

21

In [82]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.sum(a,axis=0)

array([5, 7, 9])

In [ ]:
np.sum(a,axis=1)

array([ 6, 15])

In [85]:
#reshape
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print("shape: ", before.shape)


[[1 2 3 4]
 [5 6 7 8]]
shape:  (2, 4)


In [87]:

after = before.reshape(4,2)
print(after)
print("shape: ",after.shape)
#2x4
#[1,2,3,4,5,6,7,8]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape:  (4, 2)


In [88]:
x1=before.reshape(8,1)
x1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [90]:
x1=before.reshape(1,8)
x1

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [91]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
before.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#stacking
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [ ]:
x1=np.vstack((x,y))
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [ ]:
filedata.dtype

dtype('float64')

In [ ]:
filedata = filedata.astype('int32')
print(filedata)

In [ ]:
(filedata>50) & (filedata<100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [ ]:
a=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
    [26,27,28,29,30]
])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])